In [23]:
list1 = [1,2,3,4,5]
df = pd.DataFrame(list1)
df

   0
0  1
1  2
2  3
3  4
4  5

In [26]:
list1 = ["A","B","c","j","p"]
df = pd.DataFrame(list1)
df

   0
0  A
1  B
2  c
3  j
4  p

In [7]:
import pandas as pd

# Create Series with custom index
temps = pd.Series(
    [22, 24, 19, 25, 28, 30, 27],
    index=['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
)

print(temps)
print(f"\nAverage temperature: {temps.mean():.2f}°C")

# Output:
# Mon    22
# Tue    24
# Wed    19
# Thu    25
# Fri    28
# Sat    30
# Sun    27
# dtype: int64
#
# Average temperature: 25.00°C

Mon    22
Tue    24
Wed    19
Thu    25
Fri    28
Sat    30
Sun    27
dtype: int64

Average temperature: 25.00°C

In [8]:
import pandas as pd

# Dictionary of lists approach
data = {
    'Name': ['Alice', 'Bob', 'Carol', 'David', 'Eve'],
    'Math_Score': [85, 92, 78, 88, 95],
    'Science_Score': [90, 85, 88, 92, 87],
    'Grade_Level': [9, 10, 11, 12, 10]
}

df_students = pd.DataFrame(data)
print(df_students)

# Output:
#     Name  Math_Score  Science_Score  Grade_Level
# 0  Alice          85             90            9
# 1    Bob          92             85           10
# 2  Carol          78             88           11
# 3  David          88             92           12
# 4    Eve          95             87           10

    Name  Math_Score  Science_Score  Grade_Level
0  Alice          85             90            9
1    Bob          92             85           10
2  Carol          78             88           11
3  David          88             92           12
4    Eve          95             87           10

In [9]:
#Chapter 3: Creating DataFrames
#Problem 3: Multiple Creation Methods
import pandas as pd
import numpy as np

# Method 1: Dictionary of lists (most common)
data_dict = {
    'Product': ['Laptop', 'Mouse', 'Keyboard'],
    'Price': [999, 25, 75],
    'Stock': [15, 150, 80]
}
df1 = pd.DataFrame(data_dict)
print("Method 1 - Dictionary of lists:")
print(df1)
print()

# Method 2: List of lists
data_list = [
    ['Laptop', 999, 15],
    ['Mouse', 25, 150],
    ['Keyboard', 75, 80]
]
df2 = pd.DataFrame(data_list, columns=['Product', 'Price', 'Stock'])
print("Method 2 - List of lists:")
print(df2)
print()

# Method 3: List of dictionaries
data_list_dict = [
    {'Product': 'Laptop', 'Price': 999, 'Stock': 15},
    {'Product': 'Mouse', 'Price': 25, 'Stock': 150},
    {'Product': 'Keyboard', 'Price': 75, 'Stock': 80}
]
df3 = pd.DataFrame(data_list_dict)
print("Method 3 - List of dictionaries:")
print(df3)

Method 1 - Dictionary of lists:
    Product  Price  Stock
0    Laptop    999     15
1     Mouse     25    150
2  Keyboard     75     80

Method 2 - List of lists:
    Product  Price  Stock
0    Laptop    999     15
1     Mouse     25    150
2  Keyboard     75     80

Method 3 - List of dictionaries:
    Product  Price  Stock
0    Laptop    999     15
1     Mouse     25    150
2  Keyboard     75     80

In [10]:
#Problem 4: Custom Index
import pandas as pd

data = {
    'Product': ['Laptop', 'Mouse', 'Keyboard'],
    'Price': [999, 25, 75],
    'Stock': [15, 150, 80]
}

# Create with custom index
df_products = pd.DataFrame(data, index=['ELEC001', 'ELEC002', 'ELEC003'])

print(df_products)
print()

# Access price of ELEC002 using loc
price = df_products.loc['ELEC002', 'Price']
print(f"Price of ELEC002: ${price}")

# Output:
#         Product  Price  Stock
# ELEC001  Laptop    999     15
# ELEC002   Mouse     25    150
# ELEC003  Keyboard    75     80
#
# Price of ELEC002: $25

          Product  Price  Stock
ELEC001    Laptop    999     15
ELEC002     Mouse     25    150
ELEC003  Keyboard     75     80

Price of ELEC002: $25

In [ ]:
#Data Inspection
import pandas as pd

# After loading data, ALWAYS run these 3 commands:

# 1. Check first few rows to verify data loaded correctly
print("First 5 rows:")
print(df.head())
print()

# 2. Get structure info: column types, non-null counts, memory usage
print("DataFrame info:")
df.info()
print()

# 3. Get statistical summary for numeric columns
print("Descriptive statistics:")
print(df.describe())

In [12]:
#Exploring Data
#Problem 7: Missing Data Detection
import pandas as pd
import numpy as np

# Sample data with missing values
df = pd.DataFrame({
    'A': [1, 2, np.nan, 4, 5],
    'B': [10, np.nan, np.nan, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

# 1. Check which columns have missing values
print("Columns with missing values:")
print(df.isnull().any())
print()

# 2. Count missing values per column
print("Missing values count:")
print(df.isnull().sum())
print()

# 3. Calculate percentage of missing values per column
print("Percentage of missing values:")
missing_pct = (df.isnull().sum() / len(df)) * 100
print(missing_pct)

# Output:
# Columns with missing values:
# A     True
# B     True
# C    False
# dtype: bool
#
# Missing values count:
# A    1
# B    2
# C    0
# dtype: int64
#
# Percentage of missing values:
# A    20.0
# B    40.0
# C     0.0
# dtype: float64

Columns with missing values:
A     True
B     True
C    False
dtype: bool

Missing values count:
A    1
B    2
C    0
dtype: int64

Percentage of missing values:
A    20.0
B    40.0
C     0.0
dtype: float64

In [13]:
#Problem 8: Data Understanding
# df.info() provides:
# - Index range and type
# - Column names
# - Non-null count per column
# - Data type (dtype) of each column
# - Memory usage

# 3 RED FLAGS to look for:
# 1. Non-null count < total rows → Missing values present
# 2. Numeric data stored as 'object' → Type conversion needed
# 3. Very high memory usage → Optimization opportunity

# Example:
df = pd.DataFrame({
    'ID': [1, 2, 3, 4],
    'Name': ['Alice', 'Bob', 'Carol', 'David'],
    'Salary': ['50000', '60000', '55000', '70000']  # String instead of int!
})

print("Red flag: Salary is object type but should be numeric")
df.info()  # Will show Salary as object

Red flag: Salary is object type but should be numeric
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      4 non-null      int64
 1   Name    4 non-null      object
 2   Salary  4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

In [14]:
#Selection & Indexing
#Problem 9: loc vs iloc
import pandas as pd

df = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': ['a', 'b', 'c', 'd', 'e'],
    'C': [10, 20, 30, 40, 50]
}, index=['row1', 'row2', 'row3', 'row4', 'row5'])

print("Original DataFrame:")
print(df)
print()

# 1. Row 'row3' using loc
print("1. df.loc['row3']:")
print(df.loc['row3'])
print()

# 2. Row at position 2 using iloc
print("2. df.iloc[2]:")
print(df.iloc[2])
print()

# 3. Rows 'row2' through 'row4', columns 'A' and 'C' using loc
print("3. df.loc['row2':'row4', ['A', 'C']]:")
print(df.loc['row2':'row4', ['A', 'C']])
print()

# 4. Rows at positions 1-3, columns at positions 0-1 using iloc
# Note: iloc end is EXCLUSIVE (positions 1, 2, 3 not included for rows)
print("4. df.iloc[1:4, 0:2]:")
print(df.iloc[1:4, 0:2])

# Output:
# 3. df.loc['row2':'row4', ['A', 'C']]:
#        A   C
# row2   2  20
# row3   3  30
# row4   4  40
#
# 4. df.iloc[1:4, 0:2]:
#        A  B
# row2   2  b
# row3   3  c
# row4   4  d

Original DataFrame:
      A  B   C
row1  1  a  10
row2  2  b  20
row3  3  c  30
row4  4  d  40
row5  5  e  50

1. df.loc['row3']:
A     3
B     c
C    30
Name: row3, dtype: object

2. df.iloc[2]:
A     3
B     c
C    30
Name: row3, dtype: object

3. df.loc['row2':'row4', ['A', 'C']]:
      A   C
row2  2  20
row3  3  30
row4  4  40

4. df.iloc[1:4, 0:2]:
      A  B
row2  2  b
row3  3  c
row4  4  d

In [15]:
#Statistics
# Descriptive Statistics
import pandas as pd
import numpy as np

# Sample data
df = pd.DataFrame({
    'Salary': [50000, 60000, 55000, 80000, 52000, 58000, 120000, 51000],
    'Years_Experience': [1, 3, 2, 5, 2, 3, 10, 1]
})

# 1. Calculate mean, median, std for both columns
stats = df.agg(['mean', 'median', 'std'])
print("Basic statistics:")
print(stats)
print()

# 2. Find correlation between salary and experience
correlation = df['Salary'].corr(df['Years_Experience'])
print(f"Correlation: {correlation:.3f}")
print()

# 3. Identify outliers using IQR method
def find_outliers_iqr(column):
    Q1 = column.quantile(0.25)
    Q3 = column.quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    return column[(column < lower_bound) | (column > upper_bound)]

print("Outliers in Salary:")
print(find_outliers_iqr(df['Salary']))

Basic statistics:
              Salary  Years_Experience
mean    65750.000000          3.375000
median  56500.000000          2.500000
std     23932.942032          2.973094

Correlation: 0.991

Outliers in Salary:
6    120000
Name: Salary, dtype: int64

In [16]:
#Group Statistics
import pandas as pd

# Using student data from Problem 2
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Carol', 'David', 'Eve'],
    'Math_Score': [85, 92, 78, 88, 95],
    'Science_Score': [90, 85, 88, 92, 87],
    'Grade_Level': [9, 10, 11, 12, 10]
})

# Average Math score by Grade_Level
avg_by_grade = df.groupby('Grade_Level')['Math_Score'].mean()
print("Average Math Score by Grade Level:")
print(avg_by_grade)

# Output:
# Grade_Level
# 9     85.0
# 10    93.5
# 11    78.0
# 12    88.0
# Name: Math_Score, dtype: float64

Average Math Score by Grade Level:
Grade_Level
9     85.0
10    93.5
11    78.0
12    88.0
Name: Math_Score, dtype: float64

In [17]:
#Missing Data
# Handling Missing Values
import pandas as pd
import numpy as np

# Sample data with missing ages
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Carol', 'David', 'Eve', 'Frank'],
    'Age': [15, 16, np.nan, 17, np.nan, 15],
    'Grade_Level': [9, 10, 11, 12, 9, 9]
})

print("Original with missing values:")
print(df)
print(f"\nMissing values: {df['Age'].isnull().sum()}")

# 1. Fill missing ages with median age grouped by Grade_Level
df['Age'] = df.groupby('Grade_Level')['Age'].transform(
    lambda x: x.fillna(x.median())
)

print("\nAfter filling with median by Grade_Level:")
print(df)

# 2. Verify no missing values remain
print(f"\nMissing values after fill: {df['Age'].isnull().sum()}")

# 3. Why median? It's robust to outliers. If one student was 50 years old,
#    the mean would be skewed, but median represents typical student age.

Original with missing values:
    Name   Age  Grade_Level
0  Alice  15.0            9
1    Bob  16.0           10
2  Carol   NaN           11
3  David  17.0           12
4    Eve   NaN            9
5  Frank  15.0            9

Missing values: 2

After filling with median by Grade_Level:
    Name   Age  Grade_Level
0  Alice  15.0            9
1    Bob  16.0           10
2  Carol   NaN           11
3  David  17.0           12
4    Eve  15.0            9
5  Frank  15.0            9

Missing values after fill: 1

In [19]:
#Filtering & Sorting
#Complex Filtering
import pandas as pd

# Sample sales data
df = pd.DataFrame({
    'Revenue': [1500, 800, 3000, 6000, 2500, 4500, 900],
    'Region': ['North', 'South', 'East', 'North', 'South', 'West', 'North'],
    'Product_Category': ['Electronics', 'Clothing', 'Food', 'Clothing',
                         'Electronics', 'Food', 'Clothing']
})

print("Original data:")
print(df)
print()

# Filter: Revenue 1000-5000 AND Region in (North, South) AND NOT Electronics
filtered = df[
    (df['Revenue'].between(1000, 5000)) &
    (df['Region'].isin(['North', 'South'])) &
    (df['Product_Category'] != 'Electronics')
]

print("Filtered results:")
print(filtered)

Original data:
   Revenue Region Product_Category
0     1500  North      Electronics
1      800  South         Clothing
2     3000   East             Food
3     6000  North         Clothing
4     2500  South      Electronics
5     4500   West             Food
6      900  North         Clothing

Filtered results:
Empty DataFrame
Columns: [Revenue, Region, Product_Category]
Index: []

In [20]:
#Sorting
import pandas as pd

# Sample employee data
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Carol', 'David'],
    'Department': ['IT', 'HR', 'IT', 'Finance'],
    'Salary': [70000, 50000, 80000, 60000]
})

print("Original:")
print(df)
print()

# Sort by Department (asc), then Salary (desc)
df_sorted = df.sort_values(
    by=['Department', 'Salary'],
    ascending=[True, False]
)

print("Sorted:")
print(df_sorted)
print()

# Reset index
df_sorted = df_sorted.reset_index(drop=True)
print("With reset index:")
print(df_sorted)

Original:
    Name Department  Salary
0  Alice         IT   70000
1    Bob         HR   50000
2  Carol         IT   80000
3  David    Finance   60000

Sorted:
    Name Department  Salary
3  David    Finance   60000
1    Bob         HR   50000
2  Carol         IT   80000
0  Alice         IT   70000

With reset index:
    Name Department  Salary
0  David    Finance   60000
1    Bob         HR   50000
2  Carol         IT   80000
3  Alice         IT   70000

In [21]:
#GroupBy Aggregation
import pandas as pd

# Employee data
df = pd.DataFrame({
    'Department': ['IT', 'IT', 'HR', 'HR', 'Finance', 'Finance'],
    'Role': ['Dev', 'Manager', 'Recruiter', 'Manager', 'Analyst', 'Manager'],
    'Salary': [80000, 120000, 60000, 90000, 70000, 110000],
    'Years_at_Company': [2, 5, 1, 4, 3, 6]
})

print("Employee data:")
print(df)
print()

# 1. Average salary by department
avg_salary = df.groupby('Department')['Salary'].mean()
print("1. Average Salary by Department:")
print(avg_salary)
print()

# 2. Max years at company by role within each department
max_years = df.groupby(['Department', 'Role'])['Years_at_Company'].max()
print("2. Max Years by Department and Role:")
print(max_years)
print()

# 3. Count employees per department
emp_count = df.groupby('Department').size()
print("3. Employee Count by Department:")
print(emp_count)

Employee data:
  Department       Role  Salary  Years_at_Company
0         IT        Dev   80000                 2
1         IT    Manager  120000                 5
2         HR  Recruiter   60000                 1
3         HR    Manager   90000                 4
4    Finance    Analyst   70000                 3
5    Finance    Manager  110000                 6

1. Average Salary by Department:
Department
Finance     90000.0
HR          75000.0
IT         100000.0
Name: Salary, dtype: float64

2. Max Years by Department and Role:
Department  Role
Finance     Analyst      3
            Manager      6
HR          Manager      4
            Recruiter    1
IT          Dev          2
            Manager      5
Name: Years_at_Company, dtype: int64

3. Employee Count by Department:
Department
Finance    2
HR         2
IT         2
dtype: int64

In [22]:
#Multiple Aggregations
import pandas as pd

df = pd.DataFrame({
    'Department': ['IT', 'IT', 'HR', 'HR', 'Finance', 'Finance'],
    'Salary': [80000, 120000, 60000, 90000, 70000, 110000],
    'Years_at_Company': [2, 5, 1, 4, 3, 6]
})

# Multiple aggregations with .agg()
result = df.groupby('Department').agg({
    'Salary': ['sum', 'mean', 'count'],
    'Years_at_Company': 'max'
})

# Flatten column names
result.columns = ['Total_Salary', 'Avg_Salary', 'Emp_Count', 'Max_Years']
result = result.reset_index()

print(result)

# Output:
#   Department  Total_Salary  Avg_Salary  Emp_Count  Max_Years
# 0    Finance        180000     90000.0          2          6
# 1         HR        150000     75000.0          2          4
# 2         IT        200000    100000.0          2          5

  Department  Total_Salary  Avg_Salary  Emp_Count  Max_Years
0    Finance        180000     90000.0          2          6
1         HR        150000     75000.0          2          4
2         IT        200000    100000.0          2          5